### ISSUE TITLE
Errors in schema.org/JSON-LD - pasta property undefined

### ISSUE THREAD

**Issue by pbuttigieg** [EDIorg/EDIorg-repository-index#4]
Not sure if this is the right repo, but we're getting some schema.org validator errors on the `pasta` property used in some EDI records. 

https://validator.schema.org/#url=https%3A%2F%2Fportal.edirepository.org%2Fnis%2Fmapbrowse%3Fpackageid%3Dknb-lter-cce.262.2

![image](https://github.com/user-attachments/assets/fd72f254-c460-4a75-9825-87b38eebcbc9)

![image](https://github.com/user-attachments/assets/8ba9dd09-ddf8-4b73-b1ca-c9e48b2dc70b)

This can be fixed by using an `additionalProperty` property with a `PropertyValue` type. Something like:

```json
  "additionalProperty":  {
            "@type": "PropertyValue",
            "name": "pasta",
            "value": "https://pasta.lternet.edu/package"
  }
```

**Comment by clnsmth** [comment]
@pbuttigieg, thanks for alerting us to this issue. We'll get it resolved.

**Comment by clnsmth** [comment]
The fix to this issue is live in EDI's [development portal](https://portal-d.edirepository.org/nis/home.jsp) and will be rolled out to staging and production by this Wednesday evening (MT).

**Comment by clnsmth** [comment]
@pbuttigieg, this issue has been resolved. Thanks again for reporting it.

**Comment by pbuttigieg** [comment]
Thanks @clnsmth - how can we verify ? The validation link above still reports the error

**Comment by clnsmth** [comment]
Hmmm ... I think I know what's going on. Let me get back to you.

**Comment by clnsmth** [comment]
@pbuttigieg the validation link above is now passing. 

We needed to flush the cache on these outdated JSON-LD files.

**Comment by pbuttigieg** [comment]
Many thanks @clnsmth - verified
